name: Salesforce CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Salesforce CLI
        run: |
          sfdx plugin:install @salesforce/plugin-auth@1.4.3
      - name: 'Authenticate Dev Hub'
        run: sf org login --username ${{ secrets.SFDC_USERNAME }}  --instance-url ${{ secrets.SFDC_AUTH_URL }} --set-default
      - name: Lint Lightning Web Components
        run: |
          npx eslint force-app/main/default/lwc/**/*.js

      - name: Run Apex Tests
        run: |
          sfdx force:apex:test:run --resultformat human --synchronous

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app --json
