name: Salesforce CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Salesforce CLI
        run: |
          curl https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-x64.tar.gz -o sfdx-linux-x64.tar.gz
          tar xzf sfdx-linux-x64.tar.gz
          ./sfdx/install
          export PATH=$PATH:$(pwd)/sfdx
          sfdx --version

      - name: Authenticate to Salesforce
        run: |
          echo $SFDC_PASSWORD$SFDC_SECURITY_TOKEN | sfdx force:auth:web:login --username ${{ secrets.SFDC_USERNAME }} --password-and-token ${{ secrets.SFDC_PASSWORD }}$SFDC_SECURITY_TOKEN --setdefaultdevhubusername --json

      - name: Lint Lightning Web Components
        run: |
          npx eslint force-app/main/default/lwc/**/*.js

      - name: Run Apex Tests
        run: |
          sfdx force:apex:test:run --resultformat human --synchronous

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app --json
